FROM grafana/grafana-enterprise:latest

USER root

RUN grafana-cli plugins install grafana-piechart-panel && \
    grafana-cli plugins install vertamedia-clickhouse-datasource && \
    grafana-cli plugins install grafana-polystat-panel && \
    grafana-cli plugins install grafana-clock-panel

EXPOSE 3000

USER grafana
