pipeline {
	agent {
		node {
			label '' // An empty label string means "any"
		}
	}
	// environment { }

	stages {
		stage('Sync Repo') {
			steps {
				checkout scm
			}
		}
		stage ('Logging') {
			steps {
				echo "Current branch is: ${env.GIT_BRANCH}"
			}
		}
		stage ('Tests') {
			steps {
				dir ("ci-cd/tests"){
					// sh 'trivy fs .'
				}
			}
		}
		stage ('Deploy') {
			when {
				expression { return env.GIT_BRANCH.contains ('prod') }
			}
			steps {
				dir ("ci-cd") {
					sh 'bash jenkins/scripts/deploy.sh'
				}
			}
		}
	}

	post {
		always {
			echo 'Cleanup'
		}
		success {
			echo 'Success'
		}
		failure {
			echo 'Failure'
		}
	}
}
