pipeline {
	agent {
		node {
			label '' // An empty label string means "any"
		}
	}
	environment {
		REPO_URL = 'https://github.com/your-org/your-repo.git';
		SSH_CRED_ID = "836d01e5-f47e-4801-a5e2-c274f8c511f0"
	}

	stages {
		stage('Sync Repo') {
			steps {
				dir('/personal-prod-sites') {
					withCredentials([usernamePassword(credentialsId: "${env.SSH_CRED_ID}",
					                                  usernameVariable: 'GITHUB_APP',
					                                  passwordVariable: 'GITHUB_ACCESS_TOKEN')]) {
						sh "chmod +x ${WORKSPACE}/ci-cd/jenkins/scripts/sync.sh"
						sh "${WORKSPACE}/ci-cd/jenkins/scripts/sync.sh"

						// sh '' '
						//               if [ -d ".git" ]; then
						//                   echo "Repository exists. Pulling latest changes..."
						//                   git fetch origin ${GIT_BRANCH}
						//                   git checkout ${GIT_BRANCH}
						//                   git pull origin ${GIT_BRANCH}
						//               else
						//                   echo "Repository does not exist. Cloning..."
						//                   # Use the credentials in the clone URL
						//                   git clone https://${GITHUB_APP}:${GITHUB_ACCESS_TOKEN}@github.com/your-username/your-repo.git .
						//                   git checkout ${GIT_BRANCH}
						//               fi
						//           ' ''
						// sh 'git config --global --add safe.directory /personal-prod-sites'
						// sh 'git checkout ${GIT_BRANCH}'
						// sh 'git pull origin ${GIT_BRANCH}'
					}
				}
			}
		}
		stage('Debug') {
			steps {
				echo 'Stage Debug runned!'
			}
		}
		stage('Logging') {
			steps {
				script {
					echo "Current branch is: ${env.GIT_BRANCH}"
				}
			}
		}
		stage('Deploy') {
			when {
				expression { return env.GIT_BRANCH.contains('prod') }
			}
			steps {
				dir('/personal-prod-sites/ci-cd') {
					withCredentials([usernamePassword(credentialsId: "${env.SSH_CRED_ID}",
					                                  usernameVariable: 'GITHUB_APP',
					                                  passwordVariable: 'GITHUB_ACCESS_TOKEN')]) {
						sh 'git config --global --add safe.directory /personal-prod-sites'
						sh 'git checkout ${GIT_BRANCH}'
						sh 'git pull origin ${GIT_BRANCH}'
					}
					sh 'docker compose up -d --build --remove-orphans'
				}
			}
		}
	}

	post {
		always {
			echo 'Cleanup'
		}
		success {
			echo 'Success'
		}
		failure {
			echo 'Failure'
		}
	}
}
// pipeline {
//     agent {}
//
//     stages {
//         stage('Build & Test') {
//             steps {
//                 echo 'Installing dependencies and running unit tests...'
//                 // sh 'npm install && npm test' or './gradlew test'
//             }
//         }
//
//         stage('Deploy to Staging') {
//             when { branch 'main' }
//             steps {
//                 echo "Deploying ${env.BRANCH_NAME} to Staging Environment..."
//                 // Add your deployment script/helm command here
//             }
//         }
//
//         stage('Quality Gate (Manual)') {
//             // This pauses the pipeline for human verification
//             when { branch 'main' }
//             steps {
//                 timeout(time: 1, unit: 'HOURS') {
//                     input message: "Does Staging look good? Approve for Production?", ok: "Deploy!"
//                 }
//             }
//         }
//
//         stage('Deploy to Production') {
//             when { branch 'main' }
//             steps {
//                 echo 'Deploying to Production servers...'
//                 // sh './deploy-prod.sh'
//             }
//         }
//     }
//
//     post {
//         always {
//             echo 'Cleaning up workspace...'
//         }
//         failure {
//             echo 'Pipeline failed! Sending notification to Slack/Email...'
//         }
//     }
// }
